---
title: "What makes a good test suite?"
author:
- Simon Larsén
- Philippa Örnell
date: \today
highlight: tango
theme: Madrid
numbersections: true
toc: true
csl: ieee.csl
colorlinks: true
link-citations: true
citecolor: black
linkcolor: black
urlcolor: black
toccolor: black
bibliography: ref.bib
header-includes:
- \usepackage{graphicx}
- \usepackage{amsfonts}
- \usepackage{booktabs}
- \usepackage{float}
- \usepackage{multicol}
---

